### ISSUE TITLE
NoMethodError: undefined method `root=' for ActiveModel::Serializer:Class

### ISSUE THREAD

**Issue by africanalex** [proglottis/ladder#48]
Error when running `bundle exec rake db:setup` 

fixed by changing active_model_serializer.rb file from 
`ActiveModel::Serializer.root = false
ActiveModel::ArraySerializer.root = false` 
to 
`ActiveModel::Serializer.config.adapter = :flatten_json`

source:
https://github.com/rails-api/active_model_serializers/issues/673#issuecomment-115820521

**Comment by proglottis** [comment]
Thanks for the report!

I think https://github.com/proglottis/ladder/tree/rails5 will fix this. I would have thought the locked versions of this gem would've been okay. Maybe not though.

**Comment by africanalex** [comment]
this error only happened when running locally on beta mac os
